@MyApp.API_HostAddress = https://localhost:7001

POST {{MyApp.API_HostAddress}}/api/category
Content-Type: application/json

{
    "Id": 1,
    "Name": "Drinks"
}

###

POST {{MyApp.API_HostAddress}}/api/Product
Content-Type: application/json

{
    "Id": 1,
    "Name": "Milk",
    "Price": 1.99,
    "CategoryId": 1
}

###

POST {{MyApp.API_HostAddress}}/api/Product
Content-Type: application/json

{
    "Id": 2,
    "Name": "Coffee",
    "Price": 4.99,
    "CategoryId": 1
}

###

GET {{MyApp.API_HostAddress}}/api/category/All

###

GET {{MyApp.API_HostAddress}}/api/product/All

###

@categoryName = Beverages
GET {{MyApp.API_HostAddress}}/api/category/SalesByCategory?categoryName={{categoryName}}

###

GET {{MyApp.API_HostAddress}}/api/category/Today
